server {
    listen 80;
    server_name localhost;

    # Obsługa plików statycznych wygenerowanych przez Flutter Web
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Ważne dla routingu SPA (Single Page Application) we Flutterze
        try_files $uri $uri/ /index.html;
    }

    # Proxy dla WebSocketów wysyłane do kontenera z backendem Go
    location /ws {
        proxy_pass http://backend:8080/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        # Wydłużone timeouty dla połączeń WebSocket
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }
}
